[[plugins]]
  package = "@netlify/plugin-functions"

[build]
  functions = "functions/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    og:image = "/logotaller.jpg"
